---
##
# Configures the LSS zone's build server (e.g. Jenkins).
##

- name: Configure ETL Server
  hosts: all
  become: true
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    env: "test"
    sub_zone: "app"
    sg_zone: "etl-server"
    splunk_target_layer: "app"
    # repo: "https://github.com/CMSgov/changeme.git"
    version: "master"
    var_files:
      - "group_vars/all/main.yml"
      - "group_vars/{{ env }}/vault.yml"

  tasks:
    - import_role:
        name: data_pipeline
