---

# The directory that the Blue Button Data Server will be installed to. 
data_server_dir: /usr/local/bluebutton-data-server

# The system service that will run the Blue Button Data Server's app server.
data_server_appserver_service: bluebutton-appserver

data_server_artifacts_mode: local
data_server_appserver_installer_name: wildfly-dist.tar.gz
data_server_appserver_name: wildfly-8.1.0.Final
data_server_appserver_local_dir: /tmp
data_server_appserver_management_username: someadmin
data_server_appserver_management_password: somepassword
data_server_war_name: bluebutton-data-server.war
data_server_war_local_dir: /tmp
data_server_ssl_server_genkeypair_args: '-keyalg RSA -keysize 4096 -dname cn=localhost -validity 3650'
data_server_db_url: 'jdbc:hsqldb:mem:test'
data_server_db_username: ""
data_server_db_password: ""

# The system user that the Blue Button Data Server will run as.
data_server_user: bb-data

# The extra Java VM args to start the app server (Wildfly/JBoss) with.
data_server_appserver_jvmargs: '' 

# The management port used by the app server (Wildfly/JBoss).
data_server_appserver_management_port: 9990

# The management admin credentials for the app server (Wildfly/JBoss). An empty username indicates that no authentication should be expected or used.
#data_server_appserver_management_username: ''
#data_server_appserver_management_password: ''

# The port that the app server (Wildfly/JBoss) should host HTTPS on.
data_server_appserver_https_port: 8443

# The client certs/CAs that will be authorized to connect to the server.
# At least one of these should be defined, otherwise no clients will be authorized to connect to the server.
data_server_ssl_client_cas: []
data_server_ssl_client_certificates:
  - alias: client_foo
    certificate: "{{ lookup('file', 'files/client-foo.crt.pem') }}"

# The max size of the DB connection pool for the Blue Button Data Server.
data_server_db_max_connections: 100

