---

- name: Install Pre-requisites
  yum:
    name:
      - java-1.8.0-openjdk-devel
    state: present
    use_backend: yum
  become: true

- name: Create Server User
  user:
    name: "{{ data_server_user }}"
    shell: /bin/false
  become: true

- name: Create Server Directory
  file:
    path: "{{ data_server_dir }}"
    state: directory
    owner: "{{ data_server_user }}"
    group: "{{ data_server_user }}"
    mode: u=rwx,g=rx,o=rx
  become: true

